import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { TodoItem } from 'src/app/classes/todoItem/todo-item';

@Injectable({
  providedIn: 'root'
})
export class ApiService {
  private _apiUrl;
  private getCountPathToBeAppended;
  private newPath:string;

  constructor(private http:HttpClient) { 
    this._apiUrl = "https://localhost:44347/api/DbToDoItems/";
  }

  getCountOfAllRecords() {
    this.getCountPathToBeAppended = "/getCount";

    var response= this.http.get<number>(this._apiUrl+this.getCountPathToBeAppended);
    return response;
  }

  getRecords(currentPageNo: number=1, pageCapacity:number=5, orderByAttribute:string="", searchForWord:string = "", searchInAttribute:string =""  ) 
  {
    this.newPath = this._apiUrl + "?";
    //in API the arguments are as follows
    //string inColumn = "", string forWord = "", string sortBy = "Id", int pageNo = 0, int pageSize = 5
    if (searchInAttribute != "") {
      this.newPath = this.newPath + "&&inColumn=" + searchInAttribute;
    }
    if (searchForWord != "") {
      this.newPath = this.newPath + "&&forWord=" + searchForWord;
    }
    if (orderByAttribute != "") {
      this.newPath = this.newPath+ "&&sortBy=" + searchInAttribute;
    }

    if (searchInAttribute != "") {
      this.newPath = this.newPath + "&&inColumn=" + searchInAttribute;
    }
    if (searchForWord != "" || orderByAttribute != "" || searchInAttribute != "") {
      this.newPath = this.newPath+ "&&";
    } 
    this.newPath = this.newPath + "pageNo="+ currentPageNo + "&&pageSize="+pageCapacity;

     console.log(this.newPath,"This is the api call being generated by pagination");
    var response= this.http.get<Array<TodoItem>>(this.newPath);
    this.newPath = "";
    return response;
  }
}
